routes/web.php
<?php

Route::resource('users', 'UserController');
Route::resource('books', 'BookController');
Route::resource('categories', 'CategoryController');
Route::resource('orders', 'OrderController');

Route::get('/users/search/email', 'UserController@search')->name('users.search');
Route::get('/books/search/title', 'BookController@search')->name('books.search');
Route::get('/categories/search/genre', 'CategoryController@search')->name('categories.search');
Route::get('/orders/search/pesanan', 'OrderController@search')->name('orders.search');

app/Book.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    protected $fillable = [
        'id', 'title', 'description',
        'author', 'publisher', 'cover',
        'price', 'stock'
    ];

    public function category() {
        return $this->belongsToMany('App\Category');
    }
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Book;
use App\Category;
use App\Book_Category;

class BookController extends Controller
{

    public function index()
    {
        $books = Book::paginate(5);
        return view('books.index', ['books'=>$books]);
    }

    public function create()
    {
        $categories = Category::all();
        return view('books.create',['categories'=>$categories]);
    }

    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required|max:191',
            'author' => 'required|string|max:191',
            'publisher' => 'required|max:191',
            'price' => 'required|numeric',
            'stock' => 'required|numeric',
            'description' => 'required|max:191',
            'category_name' => 'required',
            'cover' => 'required|image',
        ]);

        if($request->hasFile('cover')) {
            $gambar = $request->file('cover');
            $nama = '/picture/Book/'.time().'.'.$gambar->getClientOriginalExtension();
            $direktori = public_path('/picture/Book');
            $gambar->move($direktori, $nama);
        }

        Book::create([
            'title' => $request->title,
            'author' => $request->author,
            'publisher' => $request->publisher,
            'price' => $request->price,
            'stock' => $request->stock,
            'description' => $request->description,
            'cover' => $nama,
        ]);

        $books = Book::latest()->first();

        foreach($request->category_name as $genre) {
            Book_Category::create([
                'book_id' => $books->id,
                'category_id' => $genre
            ]);
        }
        
        return redirect('/books');
    }

    public function show($id)
    {
        $books = Book::find($id);
        return view('books.show', ['books'=>$books]);
    }

    public function edit($id)
    {
        $books = Book::find($id);
        $categories = Category::all();
        return view('books.edit', ['books'=>$books, 'categories'=>$categories]);
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'title' => 'required|max:191',
            'author' => 'required|string|max:191',
            'publisher' => 'required|max:191',
            'price' => 'required|numeric',
            'stock' => 'required|numeric',
            'description' => 'required|max:191',
            'category_name' => 'required'
        ]);

        $books = Book::find($id);
        $books->title = $request->title;
        $books->author = $request->author;
        $books->publisher = $request->publisher;
        $books->price = $request->price;
        $books->stock = $request->stock;
        $books->description = $request->description;

        if($request->hasFile('cover')) {
            $gambar = $request->file('cover');
            $nama = '/picture/Book/'.time().'.'.$gambar->getClientOriginalExtension();
            $direktori = public_path('/picture/Book');
            $gambar->move($direktori, $nama);
        } else {
            $nama = $books->cover;
        }

        $books->cover = $nama;
        $books->save();

        $books_categories = Book_Category::where('book_id', $id)->delete();

        foreach($request->category_name as $genre) {
            Book_Category::create([
                'book_id' => $id,
                'category_id' => $genre
            ]);
        }

        return redirect('/books');
    }

    public function destroy($id)
    {
        $books = Book::find($id);
        $books->delete();
        return redirect('/books');
    }

    public function search(Request $request) {
        $cari = $request->cari;

        $books =  Book::where('title','LIKE','%'.$cari.'%')->paginate();
        return view('books.index', ['books'=>$books]);
    }
}

resources/views/books/create.blade.php
@extends('templates.home')
@section('title')
	Create Book
@endsection

@section('content')
	
	<div class="container">
		<h1>Create Book</h1>
		<hr>

		<div class="card border-primary" style="max-width: 70%; margin: auto; margin-top: 40px;">
			<div class="card-header bg-primary text-white">
				<h5>Create a New Book</h5>
			</div>
			<div class="card-body">
				<div class="container text-primary">

				<form class="form-group" action="{{ route('books.store') }}" method="POST" enctype="multipart/form-data">
				@csrf
				<div class="row">
					<div class="col-md-3">
						<label for="title">Judul</label>
					</div>
					<div class="col-md-8">
						<input class="form-control" type="text" name="title" id="title">
						{{ ($errors->has('title')) ? $errors->first('title') : "" }}
					</div>
				</div>
				<br>
				<div class="row">
					<div class="col-md-3">
						<label  for="author">Pengarang</label>
					</div>
					<div class="col-md-8">
						<input class="form-control" type="text" name="author" id="author">
						{{ ($errors->has('author')) ? $errors->first('author') : "" }}
					</div>
				</div>
				<br>
				<div class="row">
					<div class="col-md-3">
						<label  for="publisher">Penerbit</label>
					</div>
					<div class="col-md-8">
						<input class="form-control" type="text" name="publisher" id="publisher">
						{{ ($errors->has('publisher')) ? $errors->first('publisher') : "" }}
					</div>
				</div>
				<br>
				<div class="row">
					<div class="col-md-3">
						<label  for="price">Harga</label>
					</div>
					<div class="col-md-8">
						<input class="form-control" type="text" name="price" id="price">
						{{ ($errors->has('price')) ? $errors->first('price') : "" }}
					</div>
				</div>
				<br>
				<div class="row">
					<div class="col-md-3">
						<label  for="stock">Stock</label>
					</div>
					<div class="col-md-8">
						<input class="form-control" type="text" name="stock" id="stock">
						{{ ($errors->has('stock')) ? $errors->first('stock') : "" }}
					</div>
				</div>
				<br>
				<div class="row">
					<div class="col-md-3">
						<label  for="description">Description</label>
					</div>
					<div class="col-md-8">
						<input class="form-control" type="textarea" name="description" id="description">
						{{ ($errors->has('description')) ? $errors->first('description') : "" }}
					</div>
				</div>
				<br>
				<div class="row">
					<div class="col-md-3">
						<label  for="category_name">Genre</label>
					</div>
					<div class="col-md-8">
						<select multiple class="form-control" name="category_name[]" id="category_name">
							@foreach ($categories as $category)
								<option value="{{ $category->id }}">{{ $category->category_name }}</option>
							@endforeach
						</select>
						{{ ($errors->has('category_name')) ? $errors->first('category_name') : "" }}
					</div>
				</div>
				<br>
				<div class="row">
					<div class="input-group mb-3">
						<div class="col-md-3 text-primary">
							Gambar
						</div>
					<div class="col-md-8">
						<div class="custom-file">
							<label for="gambar" class="custom-file-label">Gambar</label>
							<input class="custom-file-input" type="file" name="cover" id="gambar">
						</div>
						{{ ($errors->has('cover')) ? $errors->first('cover') : "" }}
					</div>
				</div>
			</div>
			<br>
			<div class="row">
				<div class="col-md-3 offset-md-5 offset-md-4">
					<button class="btn btn-outline-primary" type="submit">Create</button>
				</div>
			</div>
		</form>
	</div>
	</div>
</div>
</div>
@endsection

resources/views/books/edit.blade.php
@extends('templates.home')
@section('title')
	Edit Buku
@endsection
@section('content')

	<div class="container">
		<h1>Edit Book</h1>
		<hr>

		<div class="card border-primary" style="max-width: 70%; margin: auto; margin-top: 40px;">

		<div class="card-header bg-primary text-white">
			<h5>Edit Book Detail </h5>
		</div>

		<div class="card-body">

		<div class="container text-primary">

			<form action="{{ route('books.update', $books['id']) }}" method="POST" class="form-group" enctype="multipart/form-data">
				@csrf
				@method('PUT')

					<div class="row">
					<div class="col-md-3">
						<label class="text-primary" for="title">Judul</label>
					</div>
					<div class="col-md-8">
						<input class="form-control" type="text" name="title" id="title" value="{{ $books['title'] }}">
						{{ ($errors->has('title')) ? $errors->first('title') : "" }}
					</div>
					</div>
					<br>

					<div class="row">
					<div class="col-md-3">
						<label class="text-primary" for="author">Pengarang</label>
					</div>
					<div class="col-md-8">
						<input class="form-control" type="text" name="author" id="author" value="{{ $books['author'] }}">
						{{ ($errors->has('author')) ? $errors->first('author') : "" }}
					</div>
					</div>
					<br>

					<div class="row">
					<div class="col-md-3">
						<label class="text-primary" for="publisher">Penerbit</label>
					</div>
					<div class="col-md-8">
						<input class="form-control" type="text" name="publisher" id="publisher" value="{{ $books['publisher'] }}">
						{{ ($errors->has('publisher')) ? $errors->first('publisher') : "" }}
					</div>
					</div>
					<br>

					<div class="row">
						<div class="col-md-3">
							<label for="price" class="text-primary">Harga</label>
						</div>
						<div class="col-md-8">
							<input class="form-control" type="text" name="price" id="price" value="{{ $books['price'] }}">
							{{ ($errors->has('price')) ? $errors->first('price') : "" }}
						</div>
					</div>
					<br>

					<div class="row">
						<div class="col-md-3">
							<label for="stock" class="text-primary">Stock</label>
						</div>
						<div class="col-md-8">
							<input class="form-control" type="text" name="stock" id="stock" value="{{ $books['stock'] }}">
							{{ ($errors->has('stock')) ? $errors->first('stock') : "" }}
						</div>
					</div>
					<br>

					<div class="row">
						<div class="col-md-3">
							<label for="description" class="text-primary">Deskripsi</label>
						</div>
						<div class="col-md-8">
							<input class="form-control" type="textarea" name="description" id="description" 
							value="{{ $books['description'] }}">
							{{ ($errors->has('description')) ? $errors->first('description') : "" }}
						</div>
					</div>
					<br>

					<div class="row">
						<div class="col-md-3">
							<label for="category_name" class="text-primary">Genre</label>
						</div>
						<div class="col-md-8">
							<select multiple class="form-control" name="category_name[]" id="category_name">
								@foreach ($categories as $category)
									<option value="{{ $category->id }}">{{ $category->category_name }}</option>
								@endforeach
							</select>
							{{ ($errors->has('category_name')) ? $errors->first('category_name') : "" }}
						</div>
					</div>
					<br>

					<div class="row">
						<div class="input-group mb-3">
							<div class="col-md-3 text-primary">
								Cover
							</div>

							<div class="col-md-8">
								<img src=" {{asset($books['cover'])}} " alt="image" class="img-thumbnail" height="150px" width="150px">
								<div class="custom-file">
								<input type="file" class="custom-file-input" name="cover" id="customFile">
  									<label class="custom-file-label" for="customFile">Upload Gambar</label>
								</div>
								{{ ($errors->has('cover')) ? $errors->first('cover') : "" }}
							</div>
						</div>
					</div>

					<br>

					<div class="row">
						<div class="col-md-3 offset-md-5 offset-md-4">
							<button type="submit" class="btn btn-outline-primary">Update</button>
						</div>
					</div>

				</form>
			</div>
		</div>
	</div>
</div>
</div>
@endsection

resources/views/books/index.blade.php
@extends('templates.home')
@section('title')
	Daftar Buku
@endsection
@section('css')
	<style>
		body{
			padding-top: 30px;
		}
		th, td {
			padding: 10px;
			text-align: center;
		}
		td a{
			margin: 3px;
			align-content: center;
			color: white;
		}
		td a:hover{
			text-decoration: none;
		}
		td button{
			margin-top: 5px;
			cursor: pointer;
		}
	</style>
@endsection
@section('content')
	
	<div class="container">
		<h1>List Book </h1>
		<div class="row">
			<div class="col-md-2">
				<a class="btn btn-outline-primary" href="{{ route('books.create') }}"><span data-feather="plus-circle"></span>Create New Book<span class="sr-only">(current)</span></a>
			</div>
			<div class="col-md-8">
			<form action="{{ route('books.search') }}" class="form-inline" method="GET">
				<div class="form-group mx-sm-3 mb-2">
				<input class="form-control" name="cari" placeholder="Cari Buku...." value="{{ old('cari') }}">
				</div>
				<button class="btn btn-primary mb-2" type="submit">Cari</button>
			</form>
			</div>
		</div>
		<br>
		<div class="table-responsive">
		<table class="table table-striped">
		<thead>
			<tr class="table-primary">
				<th scope="col">ID</th>
				<th scope="col">Judul</th>
				<th scope="col">Pengarang</th>
				<th scope="col">Harga</th>
				<th scope="col">Cover</th>
				<th scope="col">Action</th>
			</tr>
		</thead>
		<tbody>
		@foreach ($books as $book)
		<tr>
			<td>{{ $book['id'] }}</td>
			<td>{{ $book['title'] }}</td>
			<td>{{ $book['author'] }}</td>
			<td>{{ $book['price'] }}</td>
			<td><img src="{{ asset($book['cover']) }}" alt="image" width="100px" height="80px"></td>
			<td>
				<a class="btn-sm btn-primary" href="{{ route('books.show', ['id'=>$book['id']]) }}"><span data-feather="eye"></span>Detail<span class="sr-only">(current)</span></a>
				<a class="btn-sm btn-success d-inline" href="{{ route('books.edit', ['id'=>$book['id']]) }}"><span data-feather="edit-2"></span>Edit<span class="sr-only">(current)</span></a>

				<form class="d-inline" onsubmit="return confirm('DELETE this user permanetly?')" action="{{ route('books.destroy', ['id'=>$book['id']]) }}" method="POST">
					@csrf
					@method('DELETE')
					<button type="submit" class="btn-sm btn-danger" value="Delete" name="submit"><span data-feather="trash"></span>Delete<span class="sr-only">(current)</span></button>
				</form>
			</td>
		</tr>
		@endforeach
		</tbody>
	</table>

	{{ $books->links() }}
</div>
</div>
@endsection

resources/views/books/show.blade.php
@extends('templates.home')
@section('title')
	Show Buku
@endsection
@section('content')

	<h1>Book Detail</h1>
	<hr>
	<br>

	<div class="card bg-white border-info" style="max-width: 70%; margin: auto; min-height: 400px;">

		<div class="row" style="padding: 25px;"">
			<div class="col-md-2 offset-md-4">
				<img src=" {{ asset($books['cover']) }} " alt="gambar" style="width:300px; height: 260px;" class="rounded">
			</div>
		</div>

		<div class="row">
			<div class="col-md-12 text-center">
				<h3> {{ $books['title'] }} </h3>
			</div>
		</div>
		<hr>

		<br>

		<div class="row">
			<div class="col-md-2 offset-md-2 col-sm-3 offset-sm-2">
				Pengarang
			</div>
			<div class="col-md-4 col-sm-4">
				{{ $books['author'] }}
			</div>
			<br>
		</div>

		<div class="row">
			<div class="col-md-2 offset-md-2 col-sm-3 offset-sm-2">
				Penerbit
			</div>
			<div class="col-md-4 col-sm-4">
				{{ $books['publisher'] }}
			</div>		
		</div>

		<div class="row">
			<div class="col-md-2 offset-md-2 col-sm-3 offset-sm-2">
				Deskripsi
			</div>
			<div class="col-md-4 col-sm-4">
				{{ $books['description'] }}
			</div>		
		</div>

		<div class="row">
			<div class="col-md-2 offset-md-2 col-sm-3 offset-sm-2">
				Genre
			</div>
			<div class="col-md-4 col-sm-4">
				<ul>
				@foreach ($books->category as $category)
					<li>{{ $category->category_name }}</li>
				@endforeach
				</ul>
			</div>		
		</div>

	</div>