routes/web.php
<?php

Route::resource('users', 'UserController');
Route::resource('books', 'BookController');
Route::resource('categories', 'CategoryController');
Route::resource('orders', 'OrderController');

Route::get('/users/search/email', 'UserController@search')->name('users.search');
Route::get('/books/search/title', 'BookController@search')->name('books.search');
Route::get('/categories/search/genre', 'CategoryController@search')->name('categories.search');
Route::get('/orders/search/pesanan', 'OrderController@search')->name('orders.search');

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    protected $fillable = [
        'id', 'user_id', 'total_price',
        'invoice_number', 'status'
    ];

    public function users() {
        return $this->belongsTo('App\User', 'user_id', 'id');
    }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Order;
use App\User;

class OrderController extends Controller
{

    public function index()
    {
        $orders = Order::with('users')->paginate(5);
        return view('orders.index',['orders'=>$orders]);
    }

    public function create()
    {
        $users = User::all();
        return view('orders.create', ['users'=>$users]);
    }

    public function store(Request $request)
    {
        $request->validate([
            'user_id' => 'required',
            'invoice_number' => 'required|min:10|max:32',
            'total_price' => 'required|numeric',
            'status' => 'required'
        ]);

        Order::create([
            'user_id' => $request->user_id,
            'invoice_number' => $request->invoice_number,
            'total_price' => $request->total_price,
            'status' => $request->status
        ]);

        return redirect('/orders');
    }


    public function show($id)
    {
        $orders = Order::with('users')->find($id);
        return view('orders.show',['orders'=>$orders]);
    }

    public function edit($id)
    {
        $orders = Order::with('users')->find($id);
        $users = User::all();
        return view('orders.edit',['orders'=>$orders, 'users'=>$users]);
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'invoice_number' => 'required|min:10|max:32',
            'user_id' => 'required',
            'total_price' => 'required|numeric',
            'status' => 'required'
        ]);

        $orders = Order::find($id);
        $orders->invoice_number = $request->invoice_number;
        $orders->user_id = $request->user_id;
        $orders->total_price = $request->total_price;
        $orders->status = $request->status;
        $orders->save();

        return redirect('/orders');
    }

    public function destroy($id)
    {
        $orders = Order::find($id);
        $orders->delete();
        return redirect('/orders');
    }
    
    public function search(Request $request) {
        $cari = $request->cari;

        $orders = Order::where('status','LIKE','%'.$cari.'%')
                        ->orWhere('invoice_number','LIKE','%'.$cari.'%')->paginate();
        return view('orders.index', ['orders'=>$orders]);
    }
}

resources/views/orders/create.blade.php
@extends('templates.home')
@section('title')
	Create Order
@endsection

@section('content')
	<div class="container">
		<h1>Create Order</h1>
		<hr>

		<div class="card border-primary" style="max-width: 70%; margin: auto; margin-top: 40px;">
			<div class="card-header bg-primary text-white">
				<h5>Create a New Order</h5>
			</div>
			<div class="card-body">
				<div class="container text-primary">

				<form class="form-group" action="{{ route('orders.store') }}" method="POST" enctype="multipart/form-data">
				@csrf
				<div class="row">
					<div class="col-md-3">
						<label  for="nama">Nama</label>
					</div>
					<div class="col-md-8">
						<select class="form-control" name="user_id" id="status">
							@foreach ($users as $user)
								<option value="{{ $user->id }}">{{ $user->username }}</option>
							@endforeach
						</select>
						{{ ($errors->has('user_id')) ? $errors->first('user_id') : "" }}
					</div>
				</div>
				<br>
				<div class="row">
					<div class="col-md-3">
						<label  for="invoice">Invoice</label>
					</div>
					<div class="col-md-8">
						<input class="form-control" type="text" name="invoice_number" id="invoice">
						{{ ($errors->has('invoice_number')) ? $errors->first('invoice_number') : "" }}
					</div>
				</div>
				<br>
				<div class="row">
					<div class="col-md-3">
						<label for="total">Total Harga</label>
					</div>
					<div class="col-md-8">
						<input class="form-control" type="text" name="total_price" id="total">
						{{ ($errors->has('total_price')) ? $errors->first('total_price') : "" }}
					</div>
				</div>
				<br>
				<div class="row">
					<div class="col-md-3">
						<label for="status">Status</label>
					</div>
					<div class="col-md-8">
						<select class="form-control" name="status" id="status">
							<option value="SUBMIT">SUBMIT</option>
							<option value="PROCESS">PROCESS</option>
							<option value="FINISH">FINISH</option>
							<option value="CANCEL">CANCEL</option>
						</select>
						{{ ($errors->has('status')) ? $errors->first('status') : "" }}
					</div>
				</div>
				<br>
				
				<br>
			<div class="row">
				<div class="col-md-3 offset-md-5 offset-md-4">
					<button class="btn btn-outline-primary" type="submit">Simpan</button>
				</div>
			</div>
		</form>
	</div>
	</div>
</div>
</div>
@endsection

resources/views/orders/edit.blade.php
@extends('templates.home')
@section('title')
	Edit Order
@endsection
@section('content')

	<div class="container">
		<h1>Edit Order</h1>
		<hr>

		<div class="card border-primary" style="max-width: 70%; margin: auto; margin-top: 40px;">

		<div class="card-header bg-primary text-white">
			<h5> Edit Order Detail </h5>
		</div>

		<div class="card-body">

		<div class="container text-primary">

			<form action="{{ route('orders.update', $orders['id']) }}" method="POST" class="form-group" enctype="multipart/form-data">
				@csrf
				@method('PUT')

				    <div class="row">
						<div class="col-md-3">
							<label class="text-primary" for="invoice">Invoice</label>
						</div>
						<div class="col-md-8">
							<input class="form-control" type="text" name="invoice_number" id="invoice" value="{{ $orders['invoice_number'] }}">
							{{ ($errors->has('invoice_number')) ? $errors->first('invoice_number') : "" }}
						</div>
					</div>

					<br>

					<div class="row">
						<div class="col-md-3">
							<label  for="nama">Nama</label>
						</div>
						<div class="col-md-8">
							<select class="form-control" name="user_id" id="status">
								@foreach ($users as $user)
									<option value="{{ $user->id }}">{{ $user->username }}</option>
								@endforeach
							</select>
							{{ ($errors->has('user_id')) ? $errors->first('user_id') : "" }}
						</div>
					</div>

					<br>

					<div class="row">
						<div class="col-md-3">
							<label for="total" class="text-primary">Total Harga	</label>
						</div>
						<div class="col-md-8">
							<input class="form-control" type="text" name="total_price" id="total" value="{{ $orders['total_price'] }}">
							{{ ($errors->has('total_price')) ? $errors->first('total_price') : "" }}
						</div>
					</div>

					<br>

					<div class="row">
						<div class="col-md-3">
							<label for="status">Status</label>
						</div>
						<div class="col-md-8">
							<select class="form-control" name="status" id="status">
								<option value="SUBMIT">SUBMIT</option>
								<option value="PROCESS">PROCESS</option>
								<option value="FINISH">FINISH</option>
								<option value="CANCEL">CANCEL</option>
							</select>
							{{ ($errors->has('status')) ? $errors->first('status') : "" }}
						</div>
					</div>

					<br>

					
				<br>
					<div class="row">
						<div class="col-md-3 offset-md-5 offset-md-4">
							<button type="submit" class="btn btn-outline-primary">Simpan</button>
						</div>
					</div>

				</form>
			</div>
		</div>
	</div>
</div>
</div>
@endsection

resources/views/orders/index.blade.php
@extends('templates.home')
@section('title')
	Daftar Order
@endsection
@section('css')
	<style>
		body{
			padding-top: 30px;
		}
		th, td {
			padding: 10px;
			text-align: center;
		}
		td a{
			margin: 3px;
			align-content: center;
			color: white;
		}
		td a:hover{
			text-decoration: none;
		}
		td button{
			margin-top: 5px;
			cursor: pointer;
		}
	</style>
@endsection
@section('content')
	<div class="container">
		<h1>Orders List</h1>
		<div class="row">
			<div class="col-md-2">
				<a class="btn btn-outline-primary" href="{{ route('orders.create') }}"><span data-feather="plus-circle"></span> Create New Order <span class="sr-only">(current)</span></a>
			</div>
			<div class="col-md-8">
			<form action="{{ route('orders.search') }}" class="form-inline" method="GET">
				<div class="form-group mx-sm-3 mb-2">
				<input class="form-control" name="cari" placeholder="Cari Pesanan...." value="{{ old('cari') }}">
				</div>
				<button class="btn btn-primary mb-2" type="submit">Cari</button>
			</form>
			</div>
		</div>
		<br>
		<div class="table-responsive">
		<table class="table table-striped">
		<thead>
			<tr class="table-primary">
				<th scope="col">Id</th>
				<th scope="col">Nama</th>
				<th scope="col">Total Harga</th>
				<th scope="col">Invoice</th>
				<th scope="col">Status</th>
				<th scope="col">Action</th>
			</tr>
		</thead>
		<tbody>
		@foreach ($orders as $order)
		<tr>
			<td>{{ $order->id }}</td>
			<td>{{ $order->users->username }}</td>
			<td>{{ $order->total_price }}</td>
			<td>{{ $order->invoice_number }}</td>
			<td>
			@if ( $order['status'] == 'PROCESS')
			<div class="p-1 mb-2 bg-warning text-dark">{{ $order['status'] }}</div>
			@elseif ( $order['status'] == "CANCEL")
			<div class="p-1 mb-2 bg-danger text-white">{{ $order['status'] }}</div>
			@elseif ( $order['status'] == "SUBMIT")
				<div class="p-1 mb-2 bg-primary text-white">{{ $order['status'] }}</div>
			@elseif ( $order['status']  == "FINISH")
				<div class="p-1 mb-2 bg-success text-white">{{ $order['status'] }}</div>
			@endif
			</td>
			<td>
				<a class="btn-sm btn-primary" href="{{ route('orders.show', ['id'=>$order['id']]) }}"><span data-feather="eye"></span>Detail<span class="sr-only">(current)</span></a>
				<a class="btn-sm btn-success d-inline" href="{{ route('orders.edit', ['id'=>$order['id']]) }}"><span data-feather="edit-2"></span>Edit<span class="sr-only">(current)</span></a>

				<form class="d-inline" onsubmit="return confirm('DELETE this order permanetly?')" action="{{ route('orders.destroy', ['id'=>$order['id']]) }}" method="POST">
					@csrf
					@method('DELETE')
					<button type="submit" class="btn-sm btn-danger" value="Delete" name="submit"><span data-feather="trash"></span>Delete<span class="sr-only">(current)</span></button>
				</form>

			</td>
		</tr>
		@endforeach
		</tbody>
	</table>

	{{ $orders->links() }}
</div>
</div>
@endsection

resources/views/orders/show.blade.php
@extends('templates.home')
@section('title')
	Show Order
@endsection
@section('content')

	<h1>Detail Order</h1>
	<hr>
	<br>

	<div class="card bg-white border-info" style="max-width: 70%; margin: auto; min-height: 400px;">

		<div class="row">
			<div class="col-md-12 text-center">
				<h3>Invoice : {{ $orders['invoice_number'] }} </h3>
			</div>
		</div>
		<hr>

		<br>

		<div class="row">
			<div class="col-md-2 offset-md-2 col-sm-3 offset-sm-2">
				Nama
			</div>
			<div class="col-md-4 col-sm-4">
				{{ $orders->users->username }}
			</div>
			<br>
		</div>

		<div class="row">
			<div class="col-md-2 offset-md-2 col-sm-3 offset-sm-2">
				Total Harga
			</div>
			<div class="col-md-4 col-sm-4">
				{{ $orders->total_price }}
			</div>		
		</div>

		<div class="row">
			<div class="col-md-2 offset-md-2 col-sm-3 offset-sm-2">
				Status
			</div>
			<div class="col-md-4 col-sm-4">
				@if ( $orders['status'] == 'PROCESS')
				<div class="p-1 mb-2 bg-warning text-dark">{{ $orders['status'] }}</div>
				@elseif ( $orders['status'] == "CANCEL")
				<div class="p-1 mb-2 bg-danger text-white">{{ $orders['status'] }}</div>
				@elseif ( $orders['status'] == "SUBMIT")
					<div class="p-1 mb-2 bg-primary text-white">{{ $orders['status'] }}</div>
				@elseif ( $orders['status']  == "FINISH")
					<div class="p-1 mb-2 bg-success text-white">{{ $orders['status'] }}</div>
				@endif
			</div>		
		</div>

		

	</div>

@endsection